url: http://danbarber.me
title: Dan Barber
author: Dan Barber
markdown: KramdownPygments

simple_search: https://duckduckgo.com/

exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

permalink: /:title

excerpt_separator: '<!-- more -->'

paginate: 10
paginate_path: "blog/page/:num"
recent_posts: 5
excerpt_link: "Read on &rarr;"

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
    - _assets/icons
  js_compressor: uglifier
  css_compressor: sass

picture:
  source: "_pictures"
  output: "assets"
  markup: "picture"
  presets:
    full-width:
      ppi: [1, 2]
      attr:
        itemprop: "image"
      source_large:
        media: "(min-width: 769px)"
        width: "800"
      source_medium:
        media: "(min-width: 480px)"
        width: "640"
      source_default:
        width: "400"


kramdown:
  input: GFM
