url: http://danbarber.me
title: Dan Barber
author: Dan Barber
markdown: kramdown
highlighter: pygments

simple_search: https://duckduckgo.com/

exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

permalink: /:title

excerpt_separator: '<!-- more -->'

paginate: 10
paginate_path: "blog/page/:num"
recent_posts: 5
excerpt_link: "Read on &rarr;"

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
    - _assets/icons

redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - smart

kramdown:
  input: GFM
