---
title: Dan Barber
timezone: UTC
baseurl: ""
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

author: Dan Barber
markdown: Kramdown
description: Web designer and developer for thoughtbot in London. Drummer and all
  round musician.

plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-assets
  - jekyll-picture-tag
  - jekyll_video_tag
  - jekyll-inline-svg
  - bourbon

simple_search: https://duckduckgo.com/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

include:
  - _redirects

permalink: ":year/:month/:day/:title"
excerpt_separator: "<!-- more -->"
paginate: 10
paginate_path: blog/page/:num
recent_posts: 5
excerpt_link: Read on &rarr;

post_layout: post
page_layout: page

post_template: post.markdown
page_template: page.markdown

jekyll-archives:
  enabled:
    - categories
  layout: page
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"
assets:
  prefix: "/assets"
  assets:
    - "*.png"
    - bundle.css
  digest: true
  sources:
    - _assets/images
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
  features:
    liquid: true

picture:
  source: _pictures
  output: assets
  markup: picture
  presets:
    full-width:
      ppi: [1, 2]
      attr:
        itemprop: image
      source_large:
        media: "(min-width: 769px)"
        width: '800'
      source_medium:
        media: "(min-width: 480px)"
        width: '640'
      source_default:
        width: '400'

    photo-square:
      ppi: [1, 2]
      attr:
        class: photo-square
        itemprop: image
      source_large:
        media: "(min-width: 769px)"
        width: '800'
      source_medium:
        media: "(min-width: 480px)"
        width: '640'
      source_default:
        width: '400'

    photo-wide:
      ppi: [1, 2]
      attr:
        class: photo-square
        itemprop: image
      source_large:
        media: "(min-width: 769px)"
        width: '1024'
      source_medium:
        media: "(min-width: 480px)"
        width: '780'
      source_default:
        width: '490'

kramdown:
  input: GFM
