#!/bin/sh

NETLIFY_CACHE_DIR="$NETLIFY_BUILD_BASE/cache"

mkdir -p "$NETLIFY_BUILD_BASE/_site/assets/blog"
mkdir -p "$NETLIFY_CACHE_DIR/assets/blog"
cp -Rf "$NETLIFY_CACHE_DIR/assets/blog/" "$NETLIFY_BUILD_BASE/_site/assets/blog/"

bundle exec rake build

cp -Rf "$NETLIFY_BUILD_BASE/_site/assets/blog/" "$NETLIFY_CACHE_DIR/assets/blog/"
