#!/bin/sh

pwd

NETLIFY_CACHE_DIR="$NETLIFY_BUILD_BASE/cache"

echo "Restoring cached blog assets"
mkdir -p "$NETLIFY_BUILD_BASE/repo/_site/assets"
mkdir -p "$NETLIFY_CACHE_DIR/assets"
cp -fR "$NETLIFY_CACHE_DIR/assets/blog" "$NETLIFY_BUILD_BASE/repo/_site/assets/"

bundle exec rake build

echo "Caching blog assets"
rm -rf "$NETLIFY_CACHE_DIR/assets/blog"
cp -fR "$NETLIFY_BUILD_BASE/repo/_site/assets/blog" "$NETLIFY_CACHE_DIR/assets/"
